# Generated by Django 6.0.2 on 2026-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
