# Generated by Django 6.0.2 on 2026-03-23 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Введите корректный email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Имя должно начинаться с заглавной буквы и содержать только буквы', regex='^[А-ЯЁA-Z][а-яёa-z]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Имя должно начинаться с заглавной буквы и содержать только буквы', regex='^[А-ЯЁA-Z][а-яёa-z]+$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Номер телефона должен быть(10 цифр после +7)', regex='^\\+7\\d{10}$')], verbose_name='phone number'),
        ),
    ]
